# Generated by Django 4.1.3 on 2022-11-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list_model',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo_list_model',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
