# Generated by Django 4.1.3 on 2022-11-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_list_model_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list_model',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo_list_model',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
