# Generated by Django 4.1.3 on 2022-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todo_list_model_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo_list_model',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
